[tool.poetry]
name = "np"
version = "0.1.0"
description = ""
authors = ["Богдан <bogdashka_06@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
